[general]
live_config_reload = true

import = [
  # "~/.config/alacritty/colors.toml", 
  "~/.config/alacritty/tokyo.toml",
  "~/.config/alacritty/fonts.toml",
]

[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dynamic_title = true
# opacity = 0.9
blur = true
decorations = "full"

[window.dimensions]
columns = 120
lines = 29

[window.padding]
x = 20
y = 10

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"
