[colors]
draw_bold_text_with_bright_colors = false

[font]
# size = 13.0
size = 16.0
# size = 18.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"
# style = "ExtraBold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
