#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
# auto_upgrade = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[palette]
   fore='#6c6c6c'
   grey='242'
   red='#FF5C57'
   yellow='#F3F99D'
   yellow2='#FFD664'
   blue='#57C7FF'
   magenta='#FF6AC1'
   cyan='#9AEDFE'
   white='#F1F1F0'
   purple='#a074c4'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true  

  [[blocks.segments]]
    type = "upgrade"
    style = "plain"
    foreground = "yellow2"
    background = "transparent"

 [[blocks.segments]]
    type = "path"
    style = "plain"
    background = "transperent"
    foreground = "p:blue"
    template = '<b>{{ .Path  }}</b>'    

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'fore'
    background = 'transperent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}<cyan>{{ if gt .Behind 0 }} ⇣{{ end }}{{ if gt .Ahead 0 }} ⇡{{ end }}</>'
    [blocks.segments.properties]
      branch_icon = '󰘬 '
      tag_icon = ' '
      commit_icon = '@'
      fetch_status = true

  [[blocks.segments]]
    type = "php"
    style = "plain"
    foreground = "purple"
    background = "transperent"
    template = "  {{ .Full }}"

  [[blocks.segments]]
    type = "lua"
    style = "plain"
    foreground = "p:blue"
    background = "transperent"
    template = "  {{ .Full }}"
  
  [[blocks.segments]]
    type = "docker"
    style = "plain"
    foreground = "p:blue"
    background = "transperent"
    template = "  {{ .Context }}"

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
  foreground = "p:blue"
  style = "plain"
  template = "{{.Icon}} " 
  type = "os"

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:yellow'
    background = 'transparent'
    template = ' {{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = 'fore'
    
    [blocks.segments.properties]
      time_format = '15:04:05'

[[blocks]]
    type = 'prompt'
    alignment = 'left'
    newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:magenta{{end}}",
  ]
    background = 'transperent'
    # template = ' ❯'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:magenta{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯❯ '
